live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x696969"
blue = "0x007FFF"
cyan = "0x00CCCC"
green = "0x03C03C"
magenta = "0xFF1493"
red = "0xFF2400"
white = "0xFFFAFA"
yellow = "0xFDFF00"

[colors.normal]
black = "0x10100E"
blue = "0x0087BD"
cyan = "0x20B2AA"
green = "0x009F6B"
magenta = "0x9A4EAE"
red = "0xC40233"
white = "0xC6C6C4"
yellow = "0xFFD700"

[colors.primary]
background = "0x10100E"
foreground = "0xC6C6C4"

[cursor]
thickness = 0.15
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 10.0

[font.normal]
family = "roboto mono"

[scrolling]
history = 10000
multiplier = 3

[window]
dynamic_title = true
opacity = 0.9
title = "Alacritty"

[window.dimensions]
columns = 120
lines = 30

[window.padding]
x = 0
y = 0
